stages:
  - build
  - test
  - package
  - deploy

image: maven:3.9.7-eclipse-temurin-21

variables:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - $maven_packages_cache
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - "target/*"
  script:
    - mvn compile

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  cache:
    paths:
      - $maven_packages_cache
  script:
    - mvn test

package:
  stage: package
  tags:
    - docker
  dependencies:
    - build
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - "target/*.war"
  cache:
    paths:
      - $maven_packages_cache
  script:
    - mvn package 


deploy_test:
  stage: deploy
  tags:
    - shell
  dependencies:
    - package
  script:
    - docker rm --force connectfour
    - docker image rm --force connectfour
    - docker-build . -t connectfour
    - docker run -d --rm --name connectfour -p 8080:8080 connectfour



    
