name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn compile -Dmaven.repo.local=.m2/repository

      - name: Create staging directory and copy artifacts
        run: mkdir -p staging && cp -r target/* staging

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: staging
          retention-days: 7
          
  test:
      runs-on: self-hosted 
      needs: build
  
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
  
        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
  
        - name: Restore Maven cache
          uses: actions/cache@v3
          with:
            path: .m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
  
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-artifact
            path: staging
  
        - name: Run tests with Maven
          run: mvn test -Dmaven.repo.local=.m2/repository

  package:
    runs-on: self-hosted  
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Restore Maven cache
        uses: actions/cache@v3
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: staging

      - name: Package with Maven
        run: mvn package -Dmaven.repo.local=.m2/repository

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-artifact
          path: target/*.war
          retention-days: 7

  deploy:
    runs-on: self-hosted  
    needs: package
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Remove existing Docker container
        run: |
          docker rm --force connectfour || true

      - name: Remove existing Docker image
        run: |
          docker image rm --force connectfour || true

      - name: Build Docker image
        run: |
          docker build . -t connectfour

      - name: Run Docker container
        run: |
          docker run -d --rm --name connectfour -p 8080:8080 connectfour

  stop_test:
    runs-on: self-hosted
    steps:
      - name: Remove existing Docker container
        run: |
          docker rm --force connectfour || true

      - name: Remove existing Docker image
        run: |
          docker image rm --force connectfour || true
